apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: easyrent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: lokia0574/easyrent-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MONGO_URI