pipeline {
agent any

environment {
    DOCKER_IMAGE_BACKEND = "lokia0574/easyrent-backend"
    DOCKER_IMAGE_FRONTEND = "lokia0574/easyrent-frontend"
}

stages {

    stage('Checkout Code') {
        steps {
            git 'https://github.com/kalyampudilokesh/EasyRent.git'
        }
    }

    stage('Build Images') {
        steps {
            sh '''
           docker build -t $DOCKER_IMAGE_BACKEND ./code/backend
           docker build -t $DOCKER_IMAGE_FRONTEND ./code/frontend
            '''
        }
    }

    stage('Test') {
        steps {
            sh 'echo "Run tests here"'
        }
    }

    stage('Security Scan') {
        steps {
            sh '''
            trivy image $DOCKER_IMAGE_BACKEND || true
            trivy image $DOCKER_IMAGE_FRONTEND || true
            '''
        }
    }

    stage('Push Images') {
        steps {
            sh '''
            docker push $DOCKER_IMAGE_BACKEND
            docker push $DOCKER_IMAGE_FRONTEND
            '''
        }
    }

    stage('Deploy to EKS') {
        steps {
            sh '''
            kubectl apply -f code/k8s/
            kubectl rollout restart deployment backend -n easyrent
            kubectl rollout restart deployment frontend -n easyrent
            '''
        }
    }
}
}
