pipeline {
agent any

environment {
    DOCKER_IMAGE_BACKEND = "lokia0574/easyrent-backend"
    DOCKER_IMAGE_FRONTEND = "lokia0574/easyrent-frontend"
}

stages {

    stage('Checkout Code') {
        steps {
            git 'https://github.com/kalyampudilokesh/EasyRent.git'
        }
    }

    stage('Build Images') {
        steps {
            sh '''
           docker build -t $DOCKER_IMAGE_BACKEND ./code/backend
           docker build -t $DOCKER_IMAGE_FRONTEND ./code/frontend
            '''
        }
    }

    stage('Test') {
        steps {
            sh 'echo "Run tests here"'
        }
    }

    stage('Security Scan') {
        steps {
            sh '''
            trivy image $DOCKER_IMAGE_BACKEND || true
            trivy image $DOCKER_IMAGE_FRONTEND || true
            '''
        }
    }

   stage('Push Images') {
    steps {
        withCredentials([usernamePassword(
            credentialsId: 'dockerhub-creds',
            usernameVariable: 'DOCKER_USER',
            passwordVariable: 'DOCKER_PASS'
        )]) {
            sh '''
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push $DOCKER_IMAGE_BACKEND
            docker push $DOCKER_IMAGE_FRONTEND
            '''
        }
    }
}

    stage('Deploy to EKS') {
    steps {
        withCredentials([[
            $class: 'AmazonWebServicesCredentialsBinding',
            credentialsId: 'aws-creds'
        ]]) {
            sh '''
            export AWS_DEFAULT_REGION=ap-south-1
            export AWS_PAGER=""

            aws eks update-kubeconfig --region ap-south-1 --name easyrent-eks

            kubectl apply -f code/k8s/ --validate=false
            kubectl rollout restart deployment backend -n easyrent
            kubectl rollout restart deployment frontend -n easyrent
            '''
        }
    }
}
}
}
